// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "24c6231fa8102e5c9bd265fc24d0427a09a315678ff93c9c91828a510d74e870")
