// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "5c852a6d593dd96618ee7134177cdfbc3fd239fd9a0215ba45ff154e73712d6e")
